"""
EXIF & AI-Generator Detection
==============================

Uses Pillow to read EXIF / PNG chunk metadata from images and flag:

  - Known AI generator software tags  (Gemini, Imagen, Stable Diffusion,
    Midjourney, DALL-E, Firefly, Runway, …)
  - Missing camera-hardware EXIF       (Make, Model, FocalLength, …)
    Genuine camera photos always carry this data; AI images rarely do.
  - PNG generation-parameter chunks    (ComfyUI / Stable Diffusion workflows)

Returns an ``ai_generator_score`` in 0-100 that is consumed by the scorer.
"""
from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

try:
    from PIL import Image
    from PIL.ExifTags import TAGS as _PIL_TAGS
    HAS_PIL = True
except ImportError:
    HAS_PIL = False
    logger.warning("Pillow not installed — EXIF / AI-generator check skipped")


# ── AI generator software name signatures (lower-case substrings) ─────────────
AI_SIGNATURES: list[str] = [
    # Google
    "gemini", "imagen", "imagegeneration", "google ai",
    # Stability AI / SD ecosystem
    "stable diffusion", "sdxl", "automatic1111", "a1111", "comfyui",
    "invokeai", "diffusers", "dreamshaper", "forge",
    # Midjourney
    "midjourney",
    # OpenAI
    "dall-e", "dall_e", "openai",
    # Adobe
    "adobe firefly", "firefly", "generative fill",
    # Runway / video AI
    "runway", "gen-2", "gen-3",
    # Microsoft / Bing
    "bing image creator", "microsoft designer", "designer.microsoft",
    # Other well-known generators
    "nightcafe", "artbreeder", "dreamstudio",
    "canva ai", "ideogram", "leonardo ai",
    "ai generated", "ai-generated", "generated by ai",
]

# Known benign editing tool substrings — don't penalise these
_BENIGN_TOOLS: tuple[str, ...] = (
    "photoshop", "lightroom", "gimp", "paint.net",
    "snapseed", "instagram", "twitter", "whatsapp",
    "samsung", "apple", "iphone", "android", "camera",
    "google camera", "pixel camera",
)

# EXIF numeric tag IDs for camera-hardware fields
_TAG_MAKE          = 271   # Camera manufacturer
_TAG_MODEL         = 272   # Camera model
_TAG_SOFTWARE      = 305   # Creating software
_TAG_FOCAL_LEN     = 37386 # Focal length
_TAG_FNUMBER       = 33437 # F-number / aperture
_TAG_EXPOSURE_TIME = 33434 # Shutter speed
_TAG_ISO           = 34855 # ISO sensitivity
_TAG_DATETIME_ORIG = 36867 # Original capture time
_TAG_GPS_INFO      = 34853 # GPS block (present on phone photos)


# ═════════════════════════════════════════════════════════════════════════════
# Public entry-point
# ═════════════════════════════════════════════════════════════════════════════

def analyze_exif(image_path: str) -> dict:
    """
    Analyse EXIF / PNG metadata for AI-generator indicators.

    Returns
    -------
    dict:
        ai_generator_score : int   0-100  (100 = confirmed AI tool tag)
        missing_camera     : bool  True   if no camera hardware EXIF found
        software_tag       : str | None   raw Software tag value
        findings           : list[str]
    """
    _empty = {
        "ai_generator_score": 0,
        "missing_camera": False,
        "software_tag": None,
        "findings": [],
    }

    if not HAS_PIL:
        return {**_empty, "findings": ["Pillow not installed — EXIF check skipped"]}

    path = Path(image_path)
    if not path.exists():
        return {**_empty, "findings": ["Image not found for EXIF analysis"]}

    ext = path.suffix.lower()

    # PNG files use tEXt / iTXt chunks instead of standard EXIF
    if ext == ".png":
        return _analyze_png(image_path)

    # ── JPEG / WEBP: standard EXIF ────────────────────────────────────────────
    try:
        img     = Image.open(image_path)
        exif_raw = img.getexif()          # PIL ExifData mapping
    except Exception as exc:
        logger.warning("EXIF read failed for %s: %s", path.name, exc)
        return {
            **_empty,
            "findings": ["EXIF data unreadable — file may be stripped or corrupt"],
        }

    findings: list[str] = []
    score = 0
    software_tag: str | None = None

    if not exif_raw:
        findings.append(
            "No EXIF metadata present — AI-generated images and screenshots "
            "frequently carry no EXIF at all"
        )
        return {
            "ai_generator_score": 35,
            "missing_camera": True,
            "software_tag": None,
            "findings": findings,
        }

    by_id: dict = dict(exif_raw.items())

    # ── Check Software tag ────────────────────────────────────────────────────
    sw_raw  = by_id.get(_TAG_SOFTWARE, "")
    software = str(sw_raw).strip() if sw_raw else ""

    if software:
        software_tag = software
        sw_lower     = software.lower()

        ai_hit = next((sig for sig in AI_SIGNATURES if sig in sw_lower), None)
        if ai_hit:
            score = 100
            findings.append(
                f"AI generator software tag detected: '{software}' — "
                "content is confirmed AI-generated"
            )
        elif not any(b in sw_lower for b in _BENIGN_TOOLS):
            # Unknown / unrecognised software — mild flag
            score += 15
            findings.append(
                f"Unrecognised software tag: '{software}' — may warrant review"
            )

    # ── Check camera-hardware EXIF ────────────────────────────────────────────
    has_make   = bool(by_id.get(_TAG_MAKE))
    has_model  = bool(by_id.get(_TAG_MODEL))
    has_focal  = bool(by_id.get(_TAG_FOCAL_LEN))
    has_fnumb  = bool(by_id.get(_TAG_FNUMBER))
    has_expo   = bool(by_id.get(_TAG_EXPOSURE_TIME))
    has_iso    = bool(by_id.get(_TAG_ISO))

    has_camera = has_make or has_model
    has_optics = has_focal or has_fnumb or has_expo or has_iso

    if not has_camera and not has_optics:
        # Complete absence of hardware metadata
        if score == 0:       # don't double-count if software tag already confirmed AI
            score += 40
        findings.append(
            "No camera make/model or optical metadata found — "
            "genuine photographs always contain hardware EXIF"
        )
        missing_camera = True

    elif not has_camera:
        if score < 100:
            score += 20
        findings.append(
            "Camera make/model absent — unusual for photos taken by a real camera"
        )
        missing_camera = True

    else:
        missing_camera = False
        if not has_optics:
            score += 8
            findings.append(
                "Camera make/model present but no exposure parameters "
                "(focal length, f-number, shutter speed) — slightly unusual"
            )

    score = min(100, max(0, score))
    return {
        "ai_generator_score": score,
        "missing_camera":     missing_camera,
        "software_tag":       software_tag,
        "findings":           findings,
    }


# ── PNG helper ────────────────────────────────────────────────────────────────

def _analyze_png(image_path: str) -> dict:
    """
    PNG images carry metadata in tEXt / iTXt chunks.
    ComfyUI / Stable Diffusion embed full generation parameters there.
    """
    findings: list[str] = []
    score = 0
    software_tag: str | None = None

    try:
        img  = Image.open(image_path)
        info = img.info or {}

        # ComfyUI / SD embed their full prompt / workflow
        ai_chunk_keys = {"parameters", "workflow", "prompt", "Prompt",
                         "sd-metadata", "generation_data"}
        if ai_chunk_keys & set(info.keys()):
            score = 90
            findings.append(
                "PNG contains embedded AI generation parameters "
                "(Stable Diffusion / ComfyUI workflow detected)"
            )

        # Software chunk
        sw = str(info.get("Software") or info.get("software") or "").strip()
        if sw:
            software_tag = sw
            ai_hit = next((sig for sig in AI_SIGNATURES if sig in sw.lower()), None)
            if ai_hit:
                score = max(score, 100)
                findings.append(f"AI generator software tag in PNG: '{sw}'")

        # Search all chunk values for AI signatures
        if score < 90:
            all_text = " ".join(str(v) for v in info.values()).lower()
            ai_hit   = next((sig for sig in AI_SIGNATURES if sig in all_text), None)
            if ai_hit:
                score = max(score, 85)
                findings.append(
                    f"AI generator signature '{ai_hit}' found inside PNG metadata"
                )

        if not info:
            score = max(score, 25)
            findings.append(
                "PNG has no metadata chunks — possible AI-generated or stripped image"
            )

    except Exception as exc:
        logger.warning("PNG metadata read error for %s: %s",
                       Path(image_path).name, exc)
        findings.append("PNG metadata could not be parsed")

    return {
        "ai_generator_score": min(100, score),
        "missing_camera":     True,   # PNGs never carry camera EXIF
        "software_tag":       software_tag,
        "findings":           findings,
    }
