"""
AI Watermark / Logo Detection  (v2 — enhanced)
===============================================

Detects AI-generator watermarks using five layered methods:

  Method 1 — Full-image pytesseract OCR with 8 preprocessing variants
              (plain, high-contrast, inverted, sharpened, OTSU, adaptive,
               CLAHE-equalised, bilateral-filtered)
  Method 2 — Regional OCR: four corners + bottom-center strip + top-center strip
              (AI tools place watermarks in different spots)
  Method 3 — Gemini 4-color HSV fingerprint (no Tesseract needed)
  Method 4 — Generic corner / edge overlay contrast detector
  Method 5 — White/grey semi-transparent overlay scan
              (catches light watermarks invisible to basic OCR)
"""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

# ── Tesseract path ────────────────────────────────────────────────────────────
_TESSERACT_PATH = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False
    logger.warning("OpenCV not installed — color-fingerprint watermark check disabled")

try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False
    logger.warning("Pillow not installed — OCR watermark check disabled")

_TESSERACT_OK = False
try:
    import pytesseract
    pytesseract.pytesseract.tesseract_cmd = _TESSERACT_PATH
    _r = subprocess.run(
        [_TESSERACT_PATH, "--version"],
        capture_output=True, timeout=5,
    )
    if _r.returncode == 0:
        _TESSERACT_OK = True
        logger.info(
            "Tesseract OCR ready: %s",
            _r.stdout.decode(errors="replace").splitlines()[0].strip(),
        )
    else:
        logger.warning("Tesseract binary returned non-zero — OCR disabled")
except FileNotFoundError:
    logger.warning("Tesseract not found at '%s'", _TESSERACT_PATH)
except Exception as exc:
    logger.warning("Tesseract init error: %s", exc)


# ── AI keyword list (expanded) ────────────────────────────────────────────────
_AI_KEYWORDS: list[str] = [
    "gemini",
    "google gemini",
    "imagen",
    "midjourney",
    "stable diffusion",
    "sdxl",
    "dall-e",
    "dall_e",
    "openai",
    "adobe firefly",
    "firefly",
    "runway",
    "gen-2",
    "gen-3",
    "bing image creator",
    "microsoft designer",
    "nightcafe",
    "dreamstudio",
    "ideogram",
    "leonardo",
    "ai generated",
    "ai-generated",
    "generated by ai",
    "made with ai",
    "created by ai",
    "made with gemini",
    "created with ai",
    "artificial intelligence",
    "flux",
    "playground ai",
    "canva ai",
    "grok",
    "bing",
    "copilot",
    "chatgpt",
    "sora",
    "pika",
    "kling",
    "haiper",
    "luma",
    "invideo",
]

# ── Gemini 4-color HSV fingerprint ────────────────────────────────────────────
_GEMINI_HSV: list[tuple[list, list]] = [
    ([100, 80,  80],  [130, 255, 255]),   # blue
    ([40,  70,  70],  [85,  255, 255]),   # green
    ([20,  100, 100], [38,  255, 255]),   # yellow-amber
    ([0,   80,  80],  [12,  255, 255]),   # red (low)
    ([168, 80,  80],  [180, 255, 255]),   # red (high wrap)
]


# ═════════════════════════════════════════════════════════════════════════════
# Public entry-point
# ═════════════════════════════════════════════════════════════════════════════

def analyze_watermark(image_path: str) -> dict:
    """
    Detect AI generator watermarks / logos in an image.

    Returns
    -------
    dict:
        ai_logo_detected : bool
        ai_logo_score    : int   0-100
        logo_source      : str | None
        detected_text    : str | None
        findings         : list[str]
    """
    base = {
        "ai_logo_detected": False,
        "ai_logo_score":    0,
        "logo_source":      None,
        "detected_text":    None,
        "findings":         [],
    }

    if not Path(image_path).exists():
        return {**base, "findings": ["Image not found for watermark analysis"]}

    findings: list[str]     = []
    score                    = 0
    logo_source: str | None  = None
    detected_text: str | None = None
    detected                 = False

    # ── Method 1: Full-image OCR ──────────────────────────────────────────────
    if _TESSERACT_OK and HAS_PIL and not detected:
        try:
            img = Image.open(image_path).convert("RGB")
            for prep, label in _ocr_variants_all(img):
                raw_text = pytesseract.image_to_string(
                    prep, config="--oem 3 --psm 3"
                )
                hit = _keyword_hit(raw_text)
                if hit:
                    score         = 100
                    detected      = True
                    logo_source   = hit.title()
                    detected_text = hit
                    findings.append(
                        f"AI watermark detected by full-image OCR ({label}): '{logo_source}'"
                    )
                    logger.info("OCR full-image hit [%s]: '%s'", label, hit)
                    break
        except Exception as exc:
            logger.warning("Full-image OCR failed: %s", exc)

    # ── Method 2: Regional OCR — corners + horizontal strips ─────────────────
    if _TESSERACT_OK and HAS_PIL and not detected:
        try:
            img   = Image.open(image_path).convert("RGB")
            iw, ih = img.size

            # Corner sizes (larger than before — some watermarks span more area)
            cw = max(200, iw // 3)
            ch = max(100, ih // 5)

            regions: dict[str, tuple] = {
                "top-left":     (0,       0,       cw,   ch),
                "top-right":    (iw - cw, 0,       iw,   ch),
                "bottom-left":  (0,       ih - ch, cw,   ih),
                "bottom-right": (iw - cw, ih - ch, iw,   ih),
                # Bottom-center strip (very common for AI watermarks)
                "bottom-center": (iw // 4, ih - ch, 3 * iw // 4, ih),
                # Top-center strip
                "top-center":    (iw // 4, 0,       3 * iw // 4, ch),
            }

            for rname, box in regions.items():
                crop = img.crop(box)
                for prep, label in _ocr_variants_all(crop, upscale_to=800):
                    raw_text = pytesseract.image_to_string(
                        prep, config="--oem 3 --psm 6"
                    )
                    hit = _keyword_hit(raw_text)
                    if hit:
                        score         = 95
                        detected      = True
                        logo_source   = hit.title()
                        detected_text = hit
                        findings.append(
                            f"AI watermark '{logo_source}' detected in "
                            f"{rname} region (OCR/{label})"
                        )
                        logger.info("OCR region hit [%s/%s]: '%s'", rname, label, hit)
                        break
                if detected:
                    break
        except Exception as exc:
            logger.warning("Regional OCR failed: %s", exc)

    # ── Method 3: Gemini 4-color HSV fingerprint ──────────────────────────────
    if HAS_CV2 and not detected:
        try:
            img_cv = cv2.imread(image_path)
            if img_cv is not None:
                gem_hit, corner_name = _gemini_color_fingerprint(img_cv)
                if gem_hit:
                    score         = 75
                    detected      = True
                    logo_source   = "Gemini"
                    detected_text = "gemini"
                    findings.append(
                        f"Gemini multi-color watermark pattern detected "
                        f"in {corner_name} corner (color fingerprint)"
                    )
        except Exception as exc:
            logger.warning("Gemini color fingerprint failed: %s", exc)

    # ── Method 4: Generic corner overlay detector ─────────────────────────────
    if HAS_CV2 and not detected:
        try:
            img_cv = cv2.imread(image_path)
            if img_cv is not None:
                ov_hit, corner_name = _corner_overlay_detector(img_cv)
                if ov_hit:
                    score    = 40
                    detected = True
                    findings.append(
                        f"Possible watermark overlay region detected "
                        f"in {corner_name} corner"
                    )
        except Exception as exc:
            logger.warning("Corner overlay detector failed: %s", exc)

    # ── Method 5: Semi-transparent white/grey overlay scan ───────────────────
    if HAS_CV2 and not detected:
        try:
            img_cv = cv2.imread(image_path)
            if img_cv is not None:
                st_hit, region_name = _semi_transparent_overlay_scan(img_cv)
                if st_hit:
                    score    = 35
                    detected = True
                    findings.append(
                        f"Semi-transparent overlay (possible watermark) "
                        f"detected in {region_name}"
                    )
        except Exception as exc:
            logger.warning("Semi-transparent overlay scan failed: %s", exc)

    return {
        "ai_logo_detected": detected,
        "ai_logo_score":    min(100, score),
        "logo_source":      logo_source,
        "detected_text":    detected_text,
        "findings":         findings if detected else [],
    }


# ── Keyword matching ──────────────────────────────────────────────────────────

def _keyword_hit(raw_text: str) -> str | None:
    """Return the first matching AI keyword found in raw_text (case-insensitive)."""
    text_lower = raw_text.lower()
    for kw in _AI_KEYWORDS:
        if kw in text_lower:
            return kw
    return None


# ── OCR preprocessing variants (enhanced) ────────────────────────────────────

def _ocr_variants_all(img: "Image.Image", upscale_to: int = 1400) -> list[tuple["Image.Image", str]]:
    """
    Return (preprocessed_image, label) pairs for OCR.
    8 variants covering: dark text, white text, coloured text, low-contrast.
    """
    from PIL import ImageFilter, ImageEnhance, ImageOps
    results: list = []

    # Ensure minimum width for reliable OCR
    w, h = img.size
    if w < upscale_to:
        scale = upscale_to / w
        img   = img.resize((int(w * scale), int(h * scale)), Image.LANCZOS)

    gray = img.convert("L")

    # Variant 1: plain grayscale
    results.append((gray, "gray"))

    # Variant 2: high-contrast
    enhanced = ImageEnhance.Contrast(gray).enhance(3.0)
    results.append((enhanced, "contrast"))

    # Variant 3: inverted (white-on-dark watermarks)
    results.append((ImageOps.invert(gray), "inverted"))

    # Variant 4: sharpened
    results.append((gray.filter(ImageFilter.SHARPEN), "sharpened"))

    # Variant 5: brightness boost then threshold (faint watermarks)
    bright = ImageEnhance.Brightness(gray).enhance(1.8)
    bright = ImageEnhance.Contrast(bright).enhance(2.5)
    results.append((bright, "brightened"))

    # Variant 6: inverted + contrast boost (white semi-transparent watermarks)
    inv_contrast = ImageEnhance.Contrast(ImageOps.invert(gray)).enhance(4.0)
    results.append((inv_contrast, "inv-contrast"))

    # OpenCV-based variants (better for complex watermarks)
    if HAS_CV2:
        import numpy as np
        from PIL import Image as PILImage

        gray_np = np.array(gray)

        # Variant 7: OTSU binary threshold
        _, otsu = cv2.threshold(gray_np, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        results.append((PILImage.fromarray(otsu), "otsu"))

        # Variant 8: Adaptive Gaussian threshold (handles uneven lighting)
        adaptive = cv2.adaptiveThreshold(
            gray_np, 255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY, 31, 10,
        )
        results.append((PILImage.fromarray(adaptive), "adaptive"))

        # Variant 9: CLAHE + OTSU (low-contrast watermarks)
        clahe   = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
        eq      = clahe.apply(gray_np)
        _, eq_t = cv2.threshold(eq, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        results.append((PILImage.fromarray(eq_t), "clahe"))

        # Variant 10: inverted adaptive (white-on-light watermarks)
        inv_adapt = cv2.bitwise_not(adaptive)
        results.append((PILImage.fromarray(inv_adapt), "inv-adaptive"))

    return results


# ── Gemini color fingerprint ──────────────────────────────────────────────────

def _gemini_color_fingerprint(img: np.ndarray) -> tuple[bool, str]:
    h, w = img.shape[:2]
    cs   = max(50, min(w, h) // 7)

    corners = {
        "bottom-right": img[h - cs:, w - cs:],
        "bottom-left":  img[h - cs:, :cs],
        "top-right":    img[:cs, w - cs:],
        "top-left":     img[:cs, :cs],
    }

    for corner_name, region in corners.items():
        if region.size == 0:
            continue
        hsv  = cv2.cvtColor(region, cv2.COLOR_BGR2HSV)
        hits = 0
        for lo, hi in _GEMINI_HSV:
            mask  = cv2.inRange(
                hsv,
                np.array(lo, dtype=np.uint8),
                np.array(hi, dtype=np.uint8),
            )
            if float(np.count_nonzero(mask)) / mask.size > 0.012:
                hits += 1
        if hits >= 3:
            return True, corner_name

    return False, ""


# ── Generic corner overlay detector ──────────────────────────────────────────

def _corner_overlay_detector(img: np.ndarray) -> tuple[bool, str]:
    h, w = img.shape[:2]
    ch   = max(40, h // 8)
    cw   = max(80, w // 5)

    corners = {
        "top-left":     img[:ch, :cw],
        "top-right":    img[:ch, w - cw:],
        "bottom-left":  img[h - ch:, :cw],
        "bottom-right": img[h - ch:, w - cw:],
        "bottom-center": img[h - ch:, w // 4: 3 * w // 4],
    }

    interior  = img[h // 4: 3 * h // 4, w // 4: 3 * w // 4]
    int_std   = float(np.std(cv2.cvtColor(interior, cv2.COLOR_BGR2GRAY))) + 1.0

    for corner_name, region in corners.items():
        if region.size == 0:
            continue
        gray    = cv2.cvtColor(region, cv2.COLOR_BGR2GRAY)
        c_std   = float(np.std(gray))
        c_mean  = float(np.mean(gray))
        lap_var = float(cv2.Laplacian(gray, cv2.CV_64F).var())

        if c_std / int_std > 2.0 and lap_var > 500 and 70 < c_mean < 240:
            return True, corner_name

    return False, ""


# ── Semi-transparent overlay scanner ─────────────────────────────────────────

def _semi_transparent_overlay_scan(img: np.ndarray) -> tuple[bool, str]:
    """
    Detect semi-transparent white/grey overlay bands (common in AI watermarks).
    Looks for image regions with high brightness and low saturation relative
    to the rest of the image — a signature of overlaid text boxes.
    """
    h, w = img.shape[:2]
    hsv  = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # Build interior reference
    interior_v = hsv[h // 4: 3 * h // 4, w // 4: 3 * w // 4, 2]
    interior_s = hsv[h // 4: 3 * h // 4, w // 4: 3 * w // 4, 1]
    ref_v_mean = float(np.mean(interior_v))
    ref_s_mean = float(np.mean(interior_s))

    band_h = max(30, h // 8)

    regions = {
        "bottom strip": hsv[h - band_h:, :],
        "top strip":    hsv[:band_h, :],
        "bottom-right corner": hsv[h - band_h:, w // 2:],
        "bottom-left corner":  hsv[h - band_h:, :w // 2],
    }

    for rname, region in regions.items():
        if region.size == 0:
            continue
        v_mean = float(np.mean(region[:, :, 2]))
        s_mean = float(np.mean(region[:, :, 1]))

        # High brightness + low saturation compared to interior → overlay
        if v_mean > ref_v_mean * 1.25 and s_mean < ref_s_mean * 0.55:
            return True, rname

    return False, ""
